# Wk 0.2 Bibliography


A page to keep track of which references are used. Note the table below aren't formatted citations, instead representing an easy way to keep track of references and the information needed to create formatted citations. Note that I intend to use a a python script in my personal library to convert tabulated reference information to .bib files.

The tables generally have the following fields:

* CitationKey (internal reference name)
* Entry type (article, book, online, misc)
* Note (personal notes on the citation)
* URL (preferably direct link to where I got it from)
* ISBN (if relevant)
* DOI (if relevant)
* Author
* Title
* bookTitle
* Publisher
* Year
* Journal

| citationKey               | entryType | note                                                                                                                                                                                                 | url                                                                                                | isbn          | doi                                          | author                                       | title                                                                                                                | year | month | publisher               | journal                                        |                                |
|---------------------------|-----------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------|---------------|----------------------------------------------|----------------------------------------------|----------------------------------------------------------------------------------------------------------------------|------|-------|-------------------------|------------------------------------------------|--------------------------------|
| labHandbook               | misc      | The physics labs Y3 handbook we are provided with – includes experiment description, deadlines and marking criteria                                                                                  |                                                                                                    |               |                                              |                                              | Level 6 Msci laboratory handbook                                                                                     | 2025 |       |                         |                                                |                                |
| labMaterials              | misc      | The resources provided on blackboard for this experiment (this is a ~ placeholder citation; ideally would find proper citations for material later, but this should help keep track of quick notes)  |                                                                                                    |               |                                              |                                              |                                                                                                                      |      |       |                         |                                                |                                |
| wildingY2                 | misc      | Content derived from Y2 "from classical to modern physics" statistical mechanics sub-module - placeholder citation for stat mech knowledge pulled from my notes                                      |                                                                                                    |               |                                              |                                              |                                                                                                                      |      |       |                         |                                                |                                |
| 9thEd                     | book      | A basic physics textbook, may be useful for physical constants or basic equations                                                                                                                    |                                                                                                    | 9781337553278 |                                              | Serway, Raymond A.                           | Physics for {Scientists} and {Engineers}                                                                             | 2018 |       | Cengage Learning        |                                                |                                |
| ComplexityAndCriticality  | book      | Recommended on bb on introductory page of lab materials                                                                                                                                              |                                                                                                    | 7309052021    |                                              | K Christensen, N R Moloney,                  | Complexity and Criticality                                                                                           | 2005 |       | Imperial College Press  |                                                |                                |
| ClusterLink1              | misc      | presentation slides outlining clustering algorithms                                                                                                                                                  | https://www.ggi.infn.it/talkfiles/slides/slides6163.pdf                                            |               |                                              |                                              |                                                                                                                      |      |       |                         |                                                |                                |
| ClusterLink2              | article   |                                                                                                                                                                                                      | https://www.sciencedirect.com/science/article/abs/pii/0003491676901597?fr=RR-2&rr=9c7220513aff93e3 |               | https://doi.org/10.1016/0003-4916(76)90159-7 | K Binder                                     | “Clusters” in the Ising model, metastable states and essential singularity                                           | 1976 |       |                         | Annals of Physics                              |                                |
| ClusterLink3              | article   |                                                                                                                                                                                                      | https://journals.aps.org/prb/pdf/10.1103/PhysRevB.17.2926                                          |               |                                              | J M Sanchez, D de Fointaine                  | The fcc ising model in the cluster variations approximation                                                          | 1978 |       |                         | Physical review B                              |                                |
| ClusterLink4              | article   |                                                                                                                                                                                                      | https://journals.aps.org/pre/pdf/10.1103/PhysRevE.71.026127                                        |               | 10.1103/PhysRevE.71.026127                   | M. B. Yilmaz, Frank M. Zimmermann            | Exact cluster size distribution in the one-dimensional Ising model                                                   | 2005 |       |                         | Physical review E                              |                                |
| ClusterDombAndStolS       | article   |                                                                                                                                                                                                      | https://iopscience.iop.org/article/10.1088/0305-4470/10/7/012/pdf                                  |               | 10.1088/0305-4470/10/7/012                   | C Domb and E Stoll                           | Shape and size of clusters in the Ising model                                                                        | 1977 |       |                         | Journal of Physics A: Mathematical and General |                                |
| ClusterLink6              | misc      |                                                                                                                                                                                                      | https://repository.tudelft.nl/file/File_62c5834c-11be-4455-a96e-e739bc6d9efa?preview=1             |               |                                              | M Delboo                                     | Using the random-cluster model for Ising model simulations                                                           | 2022 |       |                         |                                                |                                |
| CritExpLink1              | misc      |                                                                                                                                                                                                      | https://arxiv.org/pdf/2411.02604v1                                                                 |               |                                              | T Burt                                       | Computing critical exponents in 3D Ising model via pattern recognition/deep learning approach                        | 2024 |       |                         |                                                |                                |
| CritExpLink2              | article   |                                                                                                                                                                                                      | https://journals.aps.org/pre/pdf/10.1103/PhysRevE.107.034131                                       |               | 10.1103/PhysRevE.107.034131                  | Genzor, Jozef                                | Calculation of critical exponents on fractal lattice Ising model by higher-order tensor renormalization group method | 2023 |       |                         | Physical review E                              |                                |
| CritExpLink3              | article   |                                                                                                                                                                                                      | https://iopscience.iop.org/article/10.1088/0305-4470/26/20/014/pdf                                 |               | 10.1088/0305-4470/26/20/014                  | H Rieger and A P Young                       | Critical exponents of the three-dimensional random field Ising model                                                 | 1993 |       |                         | Journal of Physics A: Mathematical and General |                                |
| CritExpLink4              | misc      | Mean field theory calculation walkthrough                                                                                                                                                            | https://www2.ph.ed.ac.uk/~mevans/sp/sp10.pdf                                                       |               |                                              |                                              |                                                                                                                      |      |       |                         |                                                |                                |
| programming               | article   | wolff algorithm original paper                                                                                                                                                                       | https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.62.361                                        |               | 10.1103/PhysRevLett.62.361                   | U Wolff                                      | Collective Monte Carlo updating for spin systems                                                                     | 1989 |       |                         | Physical review letters                        |                                |
| renormalisationTutorial   | misc      | above my head atm                                                                                                                                                                                    | https://phas.ubc.ca/~seme/516/smTutorial4A.pdf                                                     |               |                                              |                                              |                                                                                                                      |      |       |                         |                                                |                                |
| isingScalingLaws          | article   | goes over the basic renormalisation stuff and power law fit methods                                                                                                                                  | https://journals.aps.org/ppf/abstract/10.1103/PhysicsPhysiqueFizika.2.263                          |               | 10.1103/PhysicsPhysiqueFizika.2.263          | Kadanoff, Leo P.                             | Scaling laws for ising models near ${T}_{c}$                                                                         | 1966 |       |                         | Physics Physique Fizika                        |                                |
| scalingCardy              | book      | goes over finite size scaling stuff                                                                                                                                                                  |                                                                                                    | 9781316036440 |                                              | John Cardy                                   | Scaling and Renormalization in Statistical Physics                                                                   |      | 2015  | Feb                     | Cambridge University Press                     |                                |
| onsagerSolutionTwo        | article   |                                                                                                                                                                                                      |                                                                                                    |               | 10.1103/PhysRev.65.117                       | L Onsager                                    | Crystal Statistics. I. A Two-Dimensional Model with an Order-Disorder Transition                                     |      | 1944  | Feb                     |                                                | Physical Review                |
| exponentsThree            | article   |                                                                                                                                                                                                      |                                                                                                    |               | https://doi.org/10.1007/JHEP03(2025)136      | hang, CH., Dommes, V., Erramilli, R.S. et al | Bootstrapping the 3d Ising stress tensor                                                                             |      | 2025  |                         |                                                | Journal of High Energy Physics |
| Mcmethods                 | book      |                                                                                                                                                                                                      |                                                                                                    | 9780198517979 |                                              | M E J Newman, G T Barkema                    | Monte Carlo methods in statistical physics                                                                           |      | 1999  |                         | Oxford University Press                        |                                |
| generalStatMech           | book      | A general textbook reference for statistical mechanics                                                                                                                                               |                                                                                                    | 9780853122722 |                                              | W. G. V Rosser                               | An introduction to statistical physics (Ellis Horwood series in mathematics and its applications)                    |      | 1982  |                         | Halsted Press                                  |                                |

