# Wk 4

## 12/02/2026 lab log

Have generated the following datasets over the past week:

* 1000 equilibration steps, 500 simulation steps:
	* 20x20
	* 30x30
	* 40x40
* 2000 equilibration steps, 500 simulation steps:
	* 20x20
	* 30x30
	* 40x40
* 3000 equilibration steps, 500 simulation steps:
	* 20x20
	* 30x30
	* 40x40
	* 50x50
	* 100x100
Furthermore, an additional 36 datapoints were added to the 3000 equilibration step datasets over a range $T \in [2,3]$


double check averaging; not weighted
scaling effect on critical exponent is result of "incorrect" apparent critical temperature; critical temperature is size dependent, not the main exponent



To do list:
* fix averaging
* fix exponent fitting
* figure out apparent vs true critical temp stuff


Averaging seems to fix it


2 methods to find "true" critical temperature (cite{labMaterials} finite-size-effects):
* fit apparent critical temperatures for different sizes using $\beta_{max} = \beta_{c} - c\cdot L^{\frac{-1}{v}}$
* Binder cumulant; $U_{l}=\frac{1 - <s^{4}>}{3<s^{2}>^{2}}$; for $T_{c} < T$, $U_{l} = 0 + O(1/V)$, for $T_{c} > T$, $U_{l} = /frac{2}{3} + O(1/V)$; at criticallity, $U_{l}$ trends towards constant
	* can find critical point by comparing $U_{l}(\beta)$ curves for different sizes; there should be an intersection point

have implemented cumulative computation; seems to work quite well, but will need to fit cumulative distribution to plot to be able to estimate data


* fixed cumulative fit
* however am encountering computational issues; as far as i can tell binder cumulant should range 


quick catchup w/Turci
* make sure to double check magnetisation over range

I am a complete idiot; it seems that when the code was discarding the configs for equilibration steps, it wasn't updating the most recent config.
Therefore the massive datasets was effectively only the last 500 steps

have fixed issue and am starting to regenerate data; have attempted multithreading, but isn't quite working; so manually setting up parallel processing.

Am currently trying to fix critical exponent fitting; as it stands cumulat seems to work reasonably well despite odd data range.
Furthermore need to wait on data generation to work on that further.

Therefore trying to fix critical exponent fitting.

Successfully implemented multithreading at the dataset object; it generates configurations in parallel; so this should accelerate dataset generation by up to a factor of 16 (currently allocating 8 threads, so should be 8x faster)

General to do list:
* generate data
* fix exponent fitting
* fully implement binder cumulate intersection function
* compute critical exponents for dimension
* generate prettier plots
* generate "final" data 
* if time allows, compute critical exponents for mean field theory model (alternatively just cite values)
* write report










unrelated thoughts; vague report structure:
* introduction
	* basic motivation
	* ising model theory
		* model statement
		* basic observables
		* existence of phase transition and critical exponents
	* metropolis algorithm theory
	* binder cumulant theory
	* critical exponent theory
	* mean field theory - note minimum derivations (if time allows)
* methods
	* briefly outline "lab process" not code architecture, but type of data generated by what methods
* results
	* include plot of apparent critical temperatures over size; use to illustrate "apparent vs true" critical temperature
	* include graph of cumulant fit intersections (demonstrate finding critical temperature)
	* include graph of magnetisations for different dimensions in same plot
	* include table of exponent values for D=1,2,3, ?4?, mean field theory
* discussion
	* TBD, depends on results, but could discuss:
		* convergence of critical exponents to mean field theory values (how quickly...)
		* slow convergence near critical temperature
		* apparent vs true critical temperature
		* computational considerations
* conclusion

will need citations for following (try and get different ones for each):
* statement of ising model
* computation for basic observables
* phase transition and critical exponents

* binder cumulant theory
* mean field theory derivation OR results
* literature values for critical exponents

* metropolis MC algorithm

* probably general textbook (complexityAndCriticality may be good)